# Change these first
owner: Bryan-Herrera-DEV # Your GitHub organization or username, where this repository lives
repo: quira-status-systems # The name of this repository

sites:
  - name: Quira Development environment
    url: https://app-dev.quira-ai.com/sign-in

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Quira Live Status Page
  introTitle: "**QUIRA | Security**"
  introMessage: Página para ver la disponibilidad de los sistemas de QUIRA
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
